# Generated by Django 4.0.dev20210428110345 on 2021-04-28 12:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('resource_link', models.URLField(blank=True, null=True)),
                ('referrer', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('locality', models.TextField()),
                ('city', models.TextField()),
                ('upvotes', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('verified', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
